// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var item;
    item = Backbone.Model.extend();
    return module.exports = item;
  });

}).call(this);
