// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var table;
    table = Backbone.Model.extend();
    return module.exports = table;
  });

}).call(this);
