// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var home;
    home = Marionette.ItemView.extend({
      template: "<div>Home<a href=\"users\">users</a></div>",
      events: {
        "click a": "jump"
      },
      jump: function(e) {
        e.preventDefault();
        return myApp.router.navigate("users/111/tile/222/ddd/333", true);
      }
    });
    return module.exports = home;
  });

}).call(this);
