// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('TablesApp', function(Tables, App) {
      var layout;
      layout = require('templates/table/table_layout.tpl');
      return Tables.Layout = Marionette.Layout.extend({
        className: 'table_layout',
        template: layout,
        regions: {
          sidebar: '#table_region_sidebar',
          content: '#table_region_content'
        }
      });
    });
  });

}).call(this);
