// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('Entities', function(Entities, App) {
      var API, initializeHeaders;
      Entities.Header = Backbone.Model.extend();
      Entities.HeaderCollection = Backbone.Collection.extend({
        model: Entities.Header
      });
      initializeHeaders = function() {
        return Entities.headers = new Entities.HeaderCollection([
          {
            name: 'Tables',
            url: 'tables'
          }, {
            name: 'About',
            url: 'about'
          }
        ]);
      };
      API = {
        getHeaders: function() {
          if ((typeof Entities.headers === 'undefined') || (Entities.header != null)) {
            return initializeHeaders();
          }
        }
      };
      return App.reqres.setHandler('header:entities', function() {
        return API.getHeaders();
      });
    });
  });

}).call(this);
