// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('Entities.tables', function(tables, App) {
      var API;
      tables.sidebarModel = Backbone.Model.extend();
      tables.sidebarCollection = Backbone.Collection.extend({
        id: 'id',
        model: tables.sidebarModel,
        setSidebarActiveStatus: function(tableId, status) {
          var model;
          if (!(_.isUndefined(tableId)) && tableId) {
            model = this.get(tableId);
            if (!(_.isUndefined(model)) && model) {
              return model.set('active', status);
            }
          }
        }
      });
      tables.contentHeaderModel = Backbone.Model.extend();
      tables.contentHeaderCollection = Backbone.Collection.extend({
        id: 'id',
        model: tables.contentHeaderModel,
        setActiveStatus: function(id, status) {
          var model;
          if (!(_.isUndefined(id)) && id) {
            model = this.get(id);
            if (!(_.isUndefined(model)) && model) {
              return model.set('active', status);
            }
          }
        }
      });
      tables.contentCreateFieldModel = Backbone.Model.extend();
      tables.contentCreateFieldCollection = Backbone.Collection.extend({
        id: 'id',
        model: tables.contentCreateFieldModel
      });
      API = {
        getSidebar: function() {
          return tables.sidebarCollections = new tables.sidebarCollection([
            {
              id: 1,
              name: '销售'
            }, {
              id: 2,
              name: '合同'
            }, {
              id: 3,
              name: '订单'
            }
          ]);
        },
        getContentHeaders: function() {
          return tables.contentHeaders = new tables.contentHeaderCollection([
            {
              id: 1,
              name: '浏览',
              type: 'view'
            }, {
              id: 2,
              name: '编辑',
              type: 'edit'
            }, {
              id: 3,
              name: '删除',
              type: 'delete'
            }
          ]);
        },
        getContentCreateFields: function(fieldsArray) {
          var contentCreateFields;
          if (fieldsArray && _.isArray(fieldsArray)) {
            return contentCreateFields = new tables.contentCreateFieldCollection(fieldsArray);
          } else {
            return contentCreateFields = new tables.contentCreateFieldCollection([
              {
                id: 1,
                name: '第一个字段',
                type: 1
              }
            ]);
          }
        }
      };
      App.reqres.setHandler('tables:sidebar', function() {
        return API.getSidebar();
      });
      App.reqres.setHandler('tables:content:headers', function() {
        return API.getContentHeaders();
      });
      return App.reqres.setHandler('tables:content:createTable', function(fieldsArray) {
        return API.getContentCreateFields(fieldsArray);
      });
    });
  });

}).call(this);
