// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var appController, homeView;
    homeView = require("views/home");
    appController = Marionette.Controller.extend({
      notFound: function() {
        console.log("notFound");
        return myApp.trigger('tables:list');
      }
    });
    return module.exports = appController;
  });

}).call(this);
