// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var app, appController, router;
    router = require('app/application_router');
    appController = require('app/application_controller');
    app = new Marionette.Application();
    app.router = app.params = app.addRegions({
      headerRegion: '#header-region',
      mainRegion: '#main-region'
    });
    app.navigate = function(route, options) {
      options = options || {};
      return Backbone.history.navigate(route, options);
    };
    app.getCurrentRoute = function() {
      return Backbone.history.fragment;
    };
    app.addInitializer(function() {
      this.router = new router({
        controller: new appController()
      });
      return null;
    });
    app.on('initialize:before', function(options) {
      return console.log("initialize:before");
    });
    app.on('initialize:after', function(options) {
      if (Backbone.history) {
        Backbone.history.start();
      }
      return console.log('initialize:after');
    });
    app.on('start', function(options) {
      return console.log('start');
    });
    return module.exports = app;
  });

}).call(this);
