// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var router;
    router = Marionette.AppRouter.extend({
      appRoutes: {
        "(*path)": "notFound"
      },
      onRoute: function(name, path, args) {
        console.log("application_router onRoute fired");
        return console.log(name, path, args);
      }
    });
    return module.exports = router;
  });

}).call(this);
