// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var LoadingView, viewHelper;
    viewHelper = require('view_helper');
    LoadingView = Marionette.ItemView.extend({
      template: viewHelper.compile('<div class="loading"><span>加载中...</span></div>')
    });
    return module.exports = LoadingView;
  });

}).call(this);
