// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('TablesApp.content', function(Content, App) {
      Content.createItem = Marionette.ItemView.extend({
        className: 'row field',
        template: require('templates/table/content/detail/create_table_field.tpl'),
        onRender: function() {
          return this.$el.attr('wj_field_id', this.model.get('id'));
        }
      });
      return Content.createView = Marionette.CompositeView.extend({
        className: 'create_view',
        template: require('templates/table/content/detail/create_table.tpl'),
        itemView: Content.createItem,
        itemViewContainer: 'div.table_fields',
        events: {
          'click .add_field': '_addFieldAction',
          'click .delete_field': '_deleteFieldAction',
          'click [wj_submit_create_table]': '_submitAction'
        },
        _addFieldAction: function(e) {
          if (_.isUndefined(this.fieldIndex)) {
            this.fieldIndex = this.collection.length + 1;
          } else {
            this.fieldIndex++;
          }
          return this.collection.add({
            id: this.fieldIndex,
            name: '',
            type: ''
          });
        },
        _deleteFieldAction: function(e) {
          var $item, fieldId;
          $item = $(e.currentTarget);
          if (this.collection.length === 1) {
            return;
          }
          fieldId = $item.attr('wj_remove_field_id');
          return this.collection.remove(fieldId);
        },
        _submitAction: function(e) {
          var formData;
          formData = form2js('create_table_form', '.', true, null);
          console.log(formData);
          this._crossDomainSubmit(formData);
          return false;
        },
        _crossDomainSubmit: function(data) {
          var url;
          url = 'http://115.28.10.1:3000';
          if (this.options.mode === 'edit') {
            url = "" + url + "/tables/" + data.id + "/update";
          } else {
            url = "" + url + "/tables/create";
          }
          WJ.ajax({
            type: "POST",
            url: url,
            dataType: 'json',
            data: data,
            xhrFields: {
              'Access-Control-Allow-Origin': '*'
            }
          }).done(function(result, textStatus, request) {
            var newTable, tableCollection;
            newTable = result.data[0];
            tableCollection = WJ.core.getCollection('table');
            tableCollection.add(newTable, {
              merge: true
            });
            url = "/tables/" + newTable.id;
            _.delay(function() {
              return App.navigate(url, {
                trigger: true
              });
            }, 500);
            console.log("Data Saved: " + newTable);
            return false;
          }).fail(function(request, textStatus, errThrown) {
            console.log("fail: " + textStatus);
            return false;
          });
          return false;
        }
      });
    });
  });

}).call(this);
