// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('TablesApp.content', function(Content, App) {
      return Content.deleteView = Marionette.ItemView.extend({
        className: 'jumbotron delete_table',
        template: require('templates/table/content/detail/delete_table.tpl'),
        events: {
          'click #delete': '_deleteAction'
        },
        _deleteAction: function(e) {
          var table_id, url;
          WJ.log("delete " + this.options.tableId);
          table_id = this.options.tableModel.get('_id');
          url = "http://115.28.10.1:3000/tables/" + this.options.tableId + "/delete";
          WJ.ajax({
            type: "POST",
            url: url,
            dataType: 'json',
            data: {
              _id: table_id
            },
            xhrFields: {
              'Access-Control-Allow-Origin': '*'
            }
          }).done((function(_this) {
            return function(result, textStatus, request) {
              var firstTableId, tableCollection;
              tableCollection = WJ.core.getCollection('table');
              tableCollection.remove(_this.options.tableId);
              if (tableCollection.length === 0) {
                url = "/tables/create";
              } else {
                firstTableId = tableCollection.at(0).get('id');
                url = "/tables/" + firstTableId;
              }
              _.delay(function() {
                return App.navigate(url, {
                  trigger: true
                });
              }, 500);
              return false;
            };
          })(this)).fail(function(request, textStatus, errThrown) {
            console.log("fail: " + textStatus);
            return false;
          });
          return false;
        }
      });
    });
  });

}).call(this);
