// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('TablesApp.content', function(Content, App) {
      Content.item = Marionette.ItemView.extend({
        className: 'item',
        template: require('templates/table/content/detail/detail_table_item.tpl')
      });
      return Content.list = Marionette.CompositeView.extend({
        className: 'table_list',
        template: require('templates/table/content/detail/detail_table.tpl'),
        itemView: Content.item,
        itemViewContainer: 'div.list'
      });
    });
  });

}).call(this);
