// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('TablesApp.content', function(Content, App) {
      Content.editItem = Marionette.ItemView.extend({
        className: 'row field',
        template: require('templates/table/content/detail/edit_table_field.tpl'),
        onRender: function() {
          return this.$el.attr('wj_field_id', this.model.get('id'));
        }
      });
      return Content.editView = Marrionette.CompositeView.extend({
        className: 'edit_view'
      });
    });
  });

}).call(this);
