// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    require('app/header/list/list_controller');
    require('app/header/list/list_view');
    return App.module('NavApp', function(Nav, App) {
      var API;
      API = {
        listNavs: function() {
          return Nav.List.controller.listNavs();
        },
        setActiveNav: function(name) {
          return Nav.List.controller.setActiveNav(name);
        }
      };
      App.commands.setHandler('set:Nav', function(name) {
        return App.NavApp.List.controller.setActiveNav(name);
      });
      return Nav.on('start', function() {
        console.log('nav_app start');
        return API.listNavs();
      });
    });
  });

}).call(this);
