// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var item, itemModel;
    itemModel = require('model/item');
    item = Backbone.Collection.extend({
      id: 'id',
      model: itemModel,
      url: '/tables/items',
      getItemsArray: function() {
        return _.cloneDeep(this.models.toJSON());
      }
    });
    return module.exports = item;
  });

}).call(this);
