// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var table, tableModel;
    tableModel = require('model/table');
    table = Backbone.Collection.extend({
      id: 'id',
      model: tableModel,
      url: '/tables/list',
      setSidebarActiveStatus: function(tableId, status) {
        var model;
        if (!(_.isUndefined(tableId)) && tableId) {
          model = this.get(tableId);
          if (!(_.isUndefined(model)) && model) {
            return model.set('active', status);
          }
        }
      }
    });
    return module.exports = table;
  });

}).call(this);
