// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exprots, module) {
    var App;
    App = require('app/application');
    return App.module('TablesApp.content', function(Content, App) {
      var layout;
      layout = require('templates/table/content/content_layout.tpl');
      return Content.Layout = Marionette.Layout.extend({
        className: 'content_layout',
        template: layout,
        regions: {
          header: '#content_region_header',
          detail: '#content_region_detail'
        },
        onRender: function() {
          var tableAction;
          tableAction = App.router.action;
          console.log('111');
          console.log(App.params);
          return console.log(App.router);
        }
      });
    });
  });

}).call(this);
