// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('NavApp.List', function(List, App) {
      List.Header = Marionette.CompositeView.extend({
        template: require('templates/header/header.tpl'),
        tagName: 'li',
        events: {
          'click a': 'navigate'
        },
        modelEvents: {
          'change': 'onRender'
        },
        navigate: function(e) {
          e.preventDefault();
          return this.trigger('navigate', this.model);
        },
        onRender: function() {
          if (this.model.get('status')) {
            return this.$el.addClass('active');
          }
        }
      });
      return List.Headers = Marionette.CompositeView.extend({
        template: require('templates/header/headers.tpl'),
        className: 'navbar navbar-inverse navbar-fixed-top',
        itemView: List.Header,
        itemViewContainer: 'ul',
        evnets: {
          'click a.brand': 'brandClicked'
        },
        brandClicked: function() {
          e.preventDefault();
          return this.trigger('brand:clicked');
        },
        setActiveNav: function(name) {
          var navModel;
          if (name) {
            navModel = _.find(this.collection.models, function(model) {
              return (model.get('url')) === name;
            });
            if (navModel) {
              return navModel.set('status', 'active');
            } else {

            }
          }
        }
      });
    });
  });

}).call(this);
