// Generated by CoffeeScript 1.7.1
(function() {
  define(function(require, exports, module) {
    var App;
    App = require('app/application');
    return App.module('NavApp.List', function(List, App) {
      return List.controller = {
        listNavs: function() {
          var headersCollection;
          headersCollection = App.request('header:entities');
          this.headers = new List.Headers({
            collection: headersCollection
          });
          return App.headerRegion.show(this.headers);
        },
        setActiveNav: function(name) {
          console.log("setActiveNav " + name);
          return this.headers.setActiveNav(name);
        }
      };
    });
  });

}).call(this);
